### ISSUE TITLE
🔥Final group capstone: set up your Kanban board [RoR]

### ISSUE THREAD

**Issue by roniy68** [roniy68/capstone-rails#15]
# Highlights 🥇 
<img src="https://media2.giphy.com/media/gEosD4s6fhCUuyfrPC/giphy.gif"/>

## What I have Done
✅ Create an empty repository for your group project.
✅ Setup [GitHub project (Kanban board)](https://docs.github.com/en/issues/organizing-your-work-with-project-boards/managing-project-boards/about-project-boards) in team repo (set up the same columns as in previous group projects).
✅ Create cards based on [the project requirements](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/business_requirements.md). Each task should be a separate card that:
✅ Each of the team members should assign themselves to the cards (and time estimate distributions should be fair - no single person should be doing all of the most time-consuming tasks).

# Team Members : 
---
### 🥇  Talha Hanif : @Talha-Hanif5666 

# Kanban : 
https://github.com/roniy68/capstone-rails/projects/1

![image](https://github.com/roniy68/capstone-rails/assets/77187003/1c982711-4949-4c20-b848-f2bee8a6399e)

## Missed anything?
- [ ] Explained the purpose of this ISSUE.
- [ ] Self reviewed the ISSUE.
- [ ] Added or updated test cases.
- [ ] Informed of breaking changes, testing and migrations (if applicable).
- [ ] Updated documentation (if applicable).
- [ ] Attached screenshots (if applicable).

## Followed Rules: 
- Made sure [no linter errors](https://github.com/microverseinc/linters-config)
-  Followed [Github Flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md)
-  Documented [professionaly](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md)
- Follow our list of [best practices for Ruby](https://github.com/microverseinc/curriculum-ruby/blob/main/articles/ruby_best_practices.md).

**Comment by Meltrust** [comment]
Hi @roniy68,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have been assigned, pointed, and have descriptions ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by roniy68** [comment]
😄 Happy Coding 👍
